name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your default branch is different

permissions:
  contents: write  # Allows GitHub Actions to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v18
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd site
          npm install

      - name: Build project
        run: |
          cd site
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd site
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
